### ISSUE TITLE
Whitelisting update server

### ISSUE THREAD

**Issue by samsapti** [TheShawnMiranda/LG-TV-Ad-Block#4]
Hi, a quick question:

From the README:

>  It also blocks the software update server in case LG comes up with some patch that allows them to bypass a DNS blocker.

Which domain is that? I want to whitelist it. Thanks!

**Comment by TheShawnMiranda** [comment]
snu.lge.com

**Comment by TheShawnMiranda** [comment]
You can also update by downloading the firmware file onto a flash drive.

**Comment by samsapti** [comment]
Cool, thanks for the quick reply!

> You can also update by downloading the firmware file onto a flash drive.

I see. However, I want to avoid as much breakage as possible, as my TV has other (non-tech savvy) users.

Also, if I want to contribute a region-specific list, what's the best way to do that? Do you prefer a seperate file?

**Comment by TheShawnMiranda** [comment]
The file I already have, named list, is the source for US users. For anything outside, create a PR with a file named list-XX where XX is the country code (ex. list-IN for India).

Sample entries would look like

0.0.0.0 in.domain.com

**Comment by samsapti** [comment]
Perfect, thanks.
