### ISSUE TITLE
What notifications?

### ISSUE THREAD

**Issue by throwaway96** [TheShawnMiranda/LG-TV-Ad-Block#6]
I'm just wondering what notifications on boot you're referring to.

They may be served via SDP. Many of the smart features rely on SDP, so blocking it causes a lot of issues (as you are aware). Providing your own substitute `<country>.lgtvsdp.com` will lessen the breakage, although I believe the Content Store still won't work. With some effort, more functionality could likely be restored (but not all, e.g. due to certificate pinning).

A better approach to removing ads and disabling telemetry/ACR on a webOS TV is rooting it, but I realize a lot of people aren't comfortable doing that for various reasons.

Also, most of the `aic` (Americas) hostnames in your list are going to have `kic` (Korea, Australia?) and `eic` (Europe etc.) counterparts.

P.S.: I suspect the ACR stuff will get even more aggressive given LG's purchase of Alphonso.

**Comment by TheShawnMiranda** [comment]
The ones that pop up on boot. And yes, there are counterparts from different continents/countries. That's why I've specified test params and opened the repo to PRs. As for root, at the moment, there's no way to downgrade firmware to root that I'm aware of.

**Comment by throwaway96** [comment]
W22O 03.33.90 is vulnerable to both [crashd](https://gist.github.com/throwaway96/e811b0f7cc2a705a5a476a8dfa45e09f) and [WTA](https://gist.github.com/throwaway96/b171240ef59d7f5fd6fb48fc6dfd2941).
